### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by wblankenship** [wblankenship/dockeri.co#3]
From https://github.com/docker/docker-registry/issues/292#issuecomment-62683898

TLS Support

ping @freewil

**Comment by tazjin** [comment]
An easy fix would also be to put Cloudflare in front of it, which now automatically hands out SSL certs to everyone. If an appropriate cache header is set that shouldn't cause any problems with outdated banners.

**Comment by wblankenship** [comment]
Agreed. Need to fix caching as well, certain sites have been caching these badges indefinitely.

**Comment by wblankenship** [comment]
I just registered an account with Cloudflare. Waiting for the ssl ticket, it may be up to 24 hours.

**Comment by tazjin** [comment]
:+1: 

I think that resolves this issue :-)

**Comment by wblankenship** [comment]
https://dockeri.co/image/wblankenship/dockeri.co is now live :-) agreed
